export const HomeObjOne = {
  id: "about",
  lightBg: false, 
  lightText: true,
  lightTextDesc: true,
  topLine: "Self-Learning ", 
  headLine: "unlimeted bla bla",
  description: "some text",
  buttonLabel: 'Get Started',
  imgStart: true,
  img: require('../../images/holy-radar.png'),
  alt: "tumolabs",
  dark:true,
  primart: true,
  darkText:false,
} 

export const HomeObjTwo = {
  id: "discober",
  lightBg: true, 
  lightText: false,
  lightTextDesc: false,
  topLine: "Self-Learning ", 
  headLine: "unlimeted bla bla",
  description: "some text",
  buttonLabel: 'Learn More',
  imgStart: false,
//   img: require('/Users/dghonyan/Desktop/software_sprint/src/images/svg-3.svg'),
  alt: "tumolabs",
  dark:false,
  primart: false,
  darkText:true,
} 

export const HomeObjThree = {
  id: "signup",
  lightBg: true, 
  lightText: false,
  lightTextDesc: false,
  topLine: "Self-Learning ", 
  headLine: "unlimeted bla bla",
  description: "some text",
  buttonLabel: 'Start Now',
  imgStart: false,
//   img: require('/Users/dghonyan/Desktop/software_sprint/src/images/svg-4.svg'),
  alt: "tumolabs",
  dark:false,
  primart: false,
  darkText:true,
} 
